name: RedstoneReporter
main: me.hawkeye.minecraft.bukkitplugins.redstonereporter.RedstoneReporter
version: 0.2
description: A bukkit server plugin for reporting redstone events.
author: Stanley Hawkeye
commands:
    rsreport:
        description: Toggles the display of all redstone events in your chat
        permission: redstonereporter.rsreport
        permission-message: You don't have the permission to view redstone events
        usage: Use /<command> to toggle displaying of redstone events in your chat
    rsblock:
        description: Toggles redstone event blocking ON
        permission: redstonereporter.rsblock
        permission-message: You don't have the permission to block redstone events
        usage: Use /<command> to block redstone events
    rsunblock:
        description: Toggles redstone event blocking OFF
        permission: redstonereporter.rsunblock
        permission-message: You don't have the permission to unblock redstone events
        usage: Use /<command> to unblock redstone events


permissions:
    redstonereporter.rsreport:
        default: op
        description: Allows you to use the rsreport command
    redstonereporter.rsblock:
        default: op
        description: Allows you to use rsblock commands
    redstonereporter.rsunblock:
        default: op
        description: Allows you to use rsunblock commands         